zdavatz/amiko-web

app/controllers/MainController.java, app/models/InteractionsData.java
Verified steps
- goto http://127.0.0.1:9000/fr
- click on interaction
- search the results 
- click on the searched result
=> Load fr db on interaction [issue 1 fix]

app/actions/MyActionCreator.java, app/assets/javascripts/amiko.helpers.js, app/controllers/MainController.java, conf/routes
=> Fix language switching

app/models/FullTextSearch.java
=> Quote ean code

app/assets/javascripts/amiko.helpers.js, app/controllers/MainController.java
=> Fix issue with highlighting html

app/assets/javascripts/amiko.searchdb.coffee, app/controllers/MainController.java, app/models/FullTextSearch.java, app/models/InteractionsData.java, app/views/main.scala.html, public/stylesheets/amiko_style.css, public/stylesheets/color-scheme.css, public/stylesheets/fulltext_style.css, public/stylesheets/interactions_css.css, public/stylesheets/main_style.css, public/stylesheets/typeahead_style.css
=> Implement Dark mode

public/stylesheets/color-scheme.css
=> Fix issue with wrong link color

app/controllers/MainController.java
=> Escape argument and handle wrong id

app/controllers/MainController.java
=> Do "diacritic insensitive" searches for titles

app/assets/javascripts/amiko.searchdb.coffee, app/models/Article.java, public/stylesheets/main_style.css
=> Search ATC when ATC code in search result is clicked

app/assets/javascripts/amiko.searchdb.coffee, app/controllers/MainController.java, app/models/Article.java, app/views/index.scala.html, conf/routes, public/stylesheets/main_style.css
=> Move to another page when searching ATC

app/controllers/MainController.java, app/views/index.scala.html, conf/application.conf
#31 #33
When you run the server with ` -Dfeature.interactions=false`, the "Interactions" function is disabled
=> Switch logo based on domain & option to hide interactions

app/controllers/MainController.java, app/models/ViewContext.java, app/views/index.scala.html
=> Change google analytics id by host

app/assets/javascripts/interaction_callbacks.coffee, app/controllers/MainController.java, app/models/InteractionsData.java, conf/routes
=> Implement EPha button

app/assets/javascripts/interaction_callbacks.coffee, app/controllers/MainController.java
=> Send language to EPha API

app/models/FullTextSearch.java, app/views/index.scala.html
=> Highlight FTS with keyword

app/assets/javascripts/amiko.helpers.js, app/models/FullTextSearch.java
Now the buttons are actual links, and it's coloured by the browser properly
=> Use <a href> for links

app/assets/javascripts/amiko.prescriptions.js, app/controllers/MainController.java, app/views/prescriptions.scala.html, conf/application.conf, conf/messages, conf/messages.de, conf/messages.fr, public/stylesheets/main_style.css
Ref #50 #60
Wenn Sie der Speichern Knopf klicken, es wird die AMK Datei in Browser speichern.
Sie können es unterladen mit der ⬇️ Knopf.
=> AMK Speichern und Localisation

app/assets/javascripts/amiko.prescriptions.js
=> List new prescription first

app/assets/javascripts/amiko.prescriptions.js, app/views/prescriptions.scala.html, conf/messages, conf/messages.de, conf/messages.fr, public/stylesheets/main_style.css
=> Fix issue with not showing note & localisation

app/assets/javascripts/amiko.prescriptions.js, app/assets/javascripts/amiko.searchdb.coffee, conf/messages.fr, conf/routes
=> Localise URL for prescription view

app/assets/javascripts/amiko.prescriptions.js
=> Fix PDF generation & double click patient

app/assets/javascripts/amiko.eprescriptions.ts, app/assets/javascripts/amiko.prescriptions.ts, public/stylesheets/main_style.css
=> Enlarge scanner and fix issue with repeated scan

app/assets/javascripts/amiko.eprescriptions.ts, app/assets/javascripts/amiko.prescriptions.ts, app/views/prescriptions.scala.html, conf/messages, conf/messages.de, conf/messages.fr, public/stylesheets/main_style.css
=> Put file input in camera view

app/assets/javascripts/amiko.eprescriptions.ts
=> Also handle CHMED16A0

app/assets/javascripts/amiko.eprescriptions.ts, app/assets/javascripts/amiko.prescriptions.ts, app/views/prescriptions.scala.html, tsconfig.json
Es sollt auch ein bisschen schneller sein
=> Show loading state and scan in parallel

app/assets/javascripts/amiko.prescriptions.ts
=> Reset file input after process

app/assets/javascripts/amiko.eprescriptions.ts, app/assets/javascripts/amiko.prescriptions.ts, app/assets/javascripts/amiko.zurroseprescription.ts, app/assets/javascripts/types.ts, app/controllers/MainController.java, app/views/prescriptions.scala.html, conf/application.conf, conf/messages, conf/messages.de, conf/messages.fr, conf/routes
#97 
- Sie sollen das Zertifikat und Passwort für Zurrose in `conf/application.conf` stellen.
- Es nun fragt "Senden an ZurRose?", nach ein QRCode zu scannen.
- Es gibt auch ein "Senden an ZurRose" Knopf für Rezept
=> "Senden an ZurRose" implementieren

app/assets/javascripts/amiko.zurroseprescription.ts
=> Set default value for patientNr & eanId

app/assets/javascripts/amiko.import.ts, app/assets/javascripts/amiko.prescriptions.ts, app/controllers/MainController.java, app/views/importpage.scala.html, conf/application.conf, conf/routes
#129 
- Sie können die URL der Sender in `application.conf` `js_prescription_import_origin` setzen. (Ich habe es zu "http://localhost:8080" setzen)
- Es kappt, wenn Ich habe Amiko-web auf localhost:9000 gelaufen, dann ein Page auf localhost:8000 mit diesen HTML gemacht.
```
<!DOCTYPE html>
<html>
<head><title>IndexedDB Injector</title></head>
<body>
<iframe id="target" src="http://localhost:9000/import" width="600" height="400"></iframe>
<script>
const data = {"prescription_hash":"4612ca98-1afa-41f2-abed-0b92e5feab06","place_date":"Zürich, 26.04.2024 (19:31:43)","operator":{"title":"Dr.med.","gln":"","given_name":"Ärtzin","family_name":"Anabelle","postal_address":"Winterthurerstrasse 52","city":"Zürich","country":"Schweiz","zip_code":"8006","phone_number":"0435400550","email_address":"zdav …
```
=> Ein Page um Rezept zu importieren mit postMessage

app/assets/javascripts/amiko.import.ts, app/assets/javascripts/amiko.prescriptions.ts, app/controllers/MainController.java, app/views/importpage.scala.html, conf/application.conf, conf/routes
#129 
Ich habe die HTML veränderte. 
Nach das Rezept importieren, es wird nun nach Rezept Page zeigen.
Sie können auch ein anderer Page zeigen.
```
<!DOCTYPE html>
<html>
<head><title>IndexedDB Injector</title></head>
<body>
Loading...
<form id="the-form" method="post" action="http://localhost:9000/import">
<input type="hidden" name="prescriptions" value='{"prescription_hash":"4612ca98-1afa-41f2-abed-0b92e5feab06","place_date":"Zürich, 26.04.2024 (19:31:43)","operator":{"title":"Dr.med.","gln":"","given_name":"Ärtzin","family_name":"Anabelle","postal_address":"Winterthurerstrasse 52","city":"Zürich","country":"Schweiz","zip_code":"8006","phone_number":"0435400550","email_address":"zdavatz@gmail.com","iban":"","vat_number":"","zsr_number":"","signature":null},"patient":{"patient_id":"0e8dc1 …
```
=> Switch to cross domain post as IndexedDB is not available in iframe
